# Generated by Django 5.1 on 2024-10-14 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XL_file_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('W', 'Web-system'), ('B', 'Bitrix24')], default='W', max_length=1)),
                ('file', models.FileField(upload_to='uploads/user_<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
