# Generated by Django 5.1 on 2024-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0002_xl_file_user_alter_xl_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='xl_file',
            name='source',
            field=models.CharField(choices=[('W', 'Web-system'), ('B', 'Bitrix24')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='xl_file',
            name='file',
            field=models.FileField(upload_to='uploads/user_<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
