# Generated by Django 5.1 on 2024-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0005_remove_bureau_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='modules',
            field=models.ManyToManyField(to='merge_files.modulesu'),
        ),
    ]
