# Generated by Django 5.1 on 2024-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0006_bureau_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesu',
            name='ophours',
            field=models.IntegerField(default=0),
        ),
    ]
