# Generated by Django 5.1 on 2024-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0003_xl_file_source_alter_xl_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSU',
            fields=[
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('bureaus', models.ManyToManyField(to='merge_files.bureau')),
            ],
        ),
        migrations.AddField(
            model_name='bureau',
            name='modules',
            field=models.ManyToManyField(to='merge_files.modulesu'),
        ),
        migrations.DeleteModel(
            name='XL_file',
        ),
    ]
