# Generated by Django 5.1 on 2024-10-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0004_bureau_modulesu_bureau_modules_delete_xl_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='modules',
        ),
    ]
