# Generated by Django 5.1 on 2024-10-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merge_files', '0007_modulesu_ophours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulesu',
            old_name='ophours',
            new_name='op_hours',
        ),
    ]
